import type { LinterDefinition } from "./types.js";
import {
  parseEslintOutput,
  parseBiomeOutput,
  parseRuffOutput,
  parseFlake8Output,
  parsePylintOutput,
  parseMypyOutput,
  parseClippyOutput,
  parseStaticcheckOutput,
  parseRubocopOutput,
  parseShellcheckOutput,
  parseStylelintOutput,
} from "./parsers.js";

export const LINTER_DEFINITIONS: LinterDefinition[] = [
  // ── ESLint ──────────────────────────────────────────────────────────
  {
    name: "eslint",
    label: "ESLint",
    languages: ["javascript", "typescript"],
    extensions: [".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".vue", ".svelte"],
    configFiles: [
      ".eslintrc",
      ".eslintrc.js",
      ".eslintrc.json",
      ".eslintrc.yml",
      ".eslintrc.yaml",
      "eslint.config.js",
      "eslint.config.mjs",
      "eslint.config.ts",
      "eslint.config.cjs",
    ],
    packageKeys: ["eslint"],
    versionCommand: "npx eslint --version",
    lintCommand: (files) => [
      "npx",
      "eslint",
      "--format",
      "json",
      "--no-error-on-unmatched-pattern",
      "--",
      ...files,
    ],
    parseOutput: parseEslintOutput,
    timeout: 15000,
  },
  // ── Biome ───────────────────────────────────────────────────────────
  {
    name: "biome",
    label: "Biome",
    languages: ["javascript", "typescript"],
    extensions: [".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"],
    configFiles: ["biome.json"],
    packageKeys: ["@biomejs/biome"],
    versionCommand: "npx @biomejs/biome --version",
    lintCommand: (files) => ["npx", "@biomejs/biome", "lint", "--reporter=json", "--", ...files],
    parseOutput: parseBiomeOutput,
    timeout: 15000,
  },
  // ── Ruff ────────────────────────────────────────────────────────────
  {
    name: "ruff",
    label: "Ruff",
    languages: ["python"],
    extensions: [".py", ".pyi", ".ipynb"],
    configFiles: ["ruff.toml", ".ruff.toml"],
    packageKeys: ["ruff"],
    projectMarkers: ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg"],
    versionCommand: "ruff --version",
    lintCommand: (files) => ["ruff", "check", "--output-format=json", "--", ...files],
    parseOutput: parseRuffOutput,
    timeout: 15000,
  },
  // ── Flake8 ──────────────────────────────────────────────────────────
  {
    name: "flake8",
    label: "Flake8",
    languages: ["python"],
    extensions: [".py", ".pyi"],
    configFiles: [".flake8", "setup.cfg", "tox.ini"],
    projectMarkers: ["pyproject.toml", "requirements.txt", "setup.py"],
    versionCommand: "flake8 --version",
    lintCommand: (files) => [
      "flake8",
      "--format",
      "%(path)s\t%(row)d\t%(col)d\t%(code)s\t%(text)s",
      "--",
      ...files,
    ],
    parseOutput: parseFlake8Output,
    timeout: 15000,
  },
  // ── Pylint ──────────────────────────────────────────────────────────
  {
    name: "pylint",
    label: "Pylint",
    languages: ["python"],
    extensions: [".py", ".pyi"],
    configFiles: [".pylintrc", "pylintrc"],
    projectMarkers: ["pyproject.toml", "setup.py"],
    versionCommand: "pylint --version",
    lintCommand: (files) => ["pylint", "--output-format=json", "--", ...files],
    parseOutput: parsePylintOutput,
    timeout: 30000,
  },
  // ── Mypy ────────────────────────────────────────────────────────────
  {
    name: "mypy",
    label: "Mypy",
    languages: ["python"],
    extensions: [".py", ".pyi"],
    configFiles: ["mypy.ini", ".mypy.ini"],
    projectMarkers: ["pyproject.toml", "setup.py"],
    versionCommand: "mypy --version",
    lintCommand: (files) => ["mypy", "--output=json", "--", ...files],
    parseOutput: parseMypyOutput,
    timeout: 30000,
  },
  // ── Clippy ──────────────────────────────────────────────────────────
  {
    name: "clippy",
    label: "Clippy",
    languages: ["rust"],
    extensions: [".rs"],
    configFiles: ["Clippy.toml", ".clippy.toml"],
    projectMarkers: ["Cargo.toml"],
    versionCommand: "cargo clippy --version",
    lintCommand: (_files) => [
      "cargo",
      "clippy",
      "--message-format=json",
      "--",
      "-W",
      "clippy::all",
    ],
    parseOutput: parseClippyOutput,
    timeout: 120000,
  },
  // ── staticcheck ─────────────────────────────────────────────────────
  {
    name: "staticcheck",
    label: "staticcheck",
    languages: ["go"],
    extensions: [".go"],
    configFiles: [],
    projectMarkers: ["go.mod"],
    versionCommand: "staticcheck -version",
    lintCommand: (files) => ["staticcheck", "-f", "json", "--", ...files],
    parseOutput: parseStaticcheckOutput,
    timeout: 30000,
  },
  // ── RuboCop ─────────────────────────────────────────────────────────
  {
    name: "rubocop",
    label: "RuboCop",
    languages: ["ruby"],
    extensions: [".rb", ".rake", ".gemspec"],
    configFiles: [".rubocop.yml"],
    projectMarkers: ["Gemfile"],
    versionCommand: "rubocop --version",
    lintCommand: (files) => ["rubocop", "--format", "json", "--", ...files],
    parseOutput: parseRubocopOutput,
    timeout: 30000,
  },
  // ── ShellCheck ──────────────────────────────────────────────────────
  {
    name: "shellcheck",
    label: "ShellCheck",
    languages: ["shell"],
    extensions: [".sh", ".bash", ".ksh", ".zsh"],
    configFiles: [".shellcheckrc"],
    projectMarkers: [],
    versionCommand: "shellcheck --version",
    lintCommand: (files) => ["shellcheck", "-f", "json", "--", ...files],
    parseOutput: parseShellcheckOutput,
    timeout: 15000,
  },
  // ── Stylelint ───────────────────────────────────────────────────────
  {
    name: "stylelint",
    label: "Stylelint",
    languages: ["css", "scss", "less"],
    extensions: [".css", ".scss", ".sass", ".less"],
    configFiles: [
      ".stylelintrc",
      ".stylelintrc.json",
      ".stylelintrc.js",
      ".stylelintrc.yml",
      ".stylelintrc.yaml",
      "stylelint.config.js",
      "stylelint.config.mjs",
      "stylelint.config.cjs",
    ],
    packageKeys: ["stylelint"],
    versionCommand: "npx stylelint --version",
    lintCommand: (files) => ["npx", "stylelint", "--formatter", "json", "--", ...files],
    parseOutput: parseStylelintOutput,
    timeout: 15000,
  },
];
